// Code generated by protoc-gen-go. DO NOT EDIT.
// source: microservcice.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// page message struct
type ModelPage struct {
	PageIdx              int32    `protobuf:"varint,1,opt,name=pageIdx,proto3" json:"pageIdx,omitempty"`
	PageSize             int32    `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Total                int32    `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModelPage) Reset()         { *m = ModelPage{} }
func (m *ModelPage) String() string { return proto.CompactTextString(m) }
func (*ModelPage) ProtoMessage()    {}
func (*ModelPage) Descriptor() ([]byte, []int) {
	return fileDescriptor_1659b64737a352e6, []int{0}
}

func (m *ModelPage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelPage.Unmarshal(m, b)
}
func (m *ModelPage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelPage.Marshal(b, m, deterministic)
}
func (m *ModelPage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelPage.Merge(m, src)
}
func (m *ModelPage) XXX_Size() int {
	return xxx_messageInfo_ModelPage.Size(m)
}
func (m *ModelPage) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelPage.DiscardUnknown(m)
}

var xxx_messageInfo_ModelPage proto.InternalMessageInfo

func (m *ModelPage) GetPageIdx() int32 {
	if m != nil {
		return m.PageIdx
	}
	return 0
}

func (m *ModelPage) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ModelPage) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

// List
type ListInfraApplyReq struct {
	PageIdx              int32    `protobuf:"varint,1,opt,name=pageIdx,proto3" json:"pageIdx,omitempty"`
	PageSize             int32    `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Search               string   `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListInfraApplyReq) Reset()         { *m = ListInfraApplyReq{} }
func (m *ListInfraApplyReq) String() string { return proto.CompactTextString(m) }
func (*ListInfraApplyReq) ProtoMessage()    {}
func (*ListInfraApplyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1659b64737a352e6, []int{1}
}

func (m *ListInfraApplyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListInfraApplyReq.Unmarshal(m, b)
}
func (m *ListInfraApplyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListInfraApplyReq.Marshal(b, m, deterministic)
}
func (m *ListInfraApplyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListInfraApplyReq.Merge(m, src)
}
func (m *ListInfraApplyReq) XXX_Size() int {
	return xxx_messageInfo_ListInfraApplyReq.Size(m)
}
func (m *ListInfraApplyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListInfraApplyReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListInfraApplyReq proto.InternalMessageInfo

func (m *ListInfraApplyReq) GetPageIdx() int32 {
	if m != nil {
		return m.PageIdx
	}
	return 0
}

func (m *ListInfraApplyReq) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListInfraApplyReq) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

type ListInfraApplyReply struct {
	Page                 *ModelPage               `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	Record               []*DetailInfraApplyReply `protobuf:"bytes,2,rep,name=record,proto3" json:"record,omitempty"`
	Exhausted            bool                     `protobuf:"varint,3,opt,name=exhausted,proto3" json:"exhausted,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ListInfraApplyReply) Reset()         { *m = ListInfraApplyReply{} }
func (m *ListInfraApplyReply) String() string { return proto.CompactTextString(m) }
func (*ListInfraApplyReply) ProtoMessage()    {}
func (*ListInfraApplyReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1659b64737a352e6, []int{2}
}

func (m *ListInfraApplyReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListInfraApplyReply.Unmarshal(m, b)
}
func (m *ListInfraApplyReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListInfraApplyReply.Marshal(b, m, deterministic)
}
func (m *ListInfraApplyReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListInfraApplyReply.Merge(m, src)
}
func (m *ListInfraApplyReply) XXX_Size() int {
	return xxx_messageInfo_ListInfraApplyReply.Size(m)
}
func (m *ListInfraApplyReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListInfraApplyReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListInfraApplyReply proto.InternalMessageInfo

func (m *ListInfraApplyReply) GetPage() *ModelPage {
	if m != nil {
		return m.Page
	}
	return nil
}

func (m *ListInfraApplyReply) GetRecord() []*DetailInfraApplyReply {
	if m != nil {
		return m.Record
	}
	return nil
}

func (m *ListInfraApplyReply) GetExhausted() bool {
	if m != nil {
		return m.Exhausted
	}
	return false
}

type DetailInfraApplyReply struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	DeviceCode           string   `protobuf:"bytes,2,opt,name=deviceCode,proto3" json:"deviceCode,omitempty"`
	Applyer              string   `protobuf:"bytes,3,opt,name=applyer,proto3" json:"applyer,omitempty"`
	Status               string   `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	SubjectName          string   `protobuf:"bytes,5,opt,name=subjectName,proto3" json:"subjectName,omitempty"`
	ReviewId             string   `protobuf:"bytes,6,opt,name=reviewId,proto3" json:"reviewId,omitempty"`
	ExpireTM             string   `protobuf:"bytes,7,opt,name=expireTM,proto3" json:"expireTM,omitempty"`
	ReviewTM             string   `protobuf:"bytes,8,opt,name=reviewTM,proto3" json:"reviewTM,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetailInfraApplyReply) Reset()         { *m = DetailInfraApplyReply{} }
func (m *DetailInfraApplyReply) String() string { return proto.CompactTextString(m) }
func (*DetailInfraApplyReply) ProtoMessage()    {}
func (*DetailInfraApplyReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1659b64737a352e6, []int{3}
}

func (m *DetailInfraApplyReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailInfraApplyReply.Unmarshal(m, b)
}
func (m *DetailInfraApplyReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailInfraApplyReply.Marshal(b, m, deterministic)
}
func (m *DetailInfraApplyReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailInfraApplyReply.Merge(m, src)
}
func (m *DetailInfraApplyReply) XXX_Size() int {
	return xxx_messageInfo_DetailInfraApplyReply.Size(m)
}
func (m *DetailInfraApplyReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailInfraApplyReply.DiscardUnknown(m)
}

var xxx_messageInfo_DetailInfraApplyReply proto.InternalMessageInfo

func (m *DetailInfraApplyReply) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *DetailInfraApplyReply) GetDeviceCode() string {
	if m != nil {
		return m.DeviceCode
	}
	return ""
}

func (m *DetailInfraApplyReply) GetApplyer() string {
	if m != nil {
		return m.Applyer
	}
	return ""
}

func (m *DetailInfraApplyReply) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *DetailInfraApplyReply) GetSubjectName() string {
	if m != nil {
		return m.SubjectName
	}
	return ""
}

func (m *DetailInfraApplyReply) GetReviewId() string {
	if m != nil {
		return m.ReviewId
	}
	return ""
}

func (m *DetailInfraApplyReply) GetExpireTM() string {
	if m != nil {
		return m.ExpireTM
	}
	return ""
}

func (m *DetailInfraApplyReply) GetReviewTM() string {
	if m != nil {
		return m.ReviewTM
	}
	return ""
}

// Add
type AddInfraApplyReq struct {
	DeviceCode           string   `protobuf:"bytes,1,opt,name=deviceCode,proto3" json:"deviceCode,omitempty"`
	Uid                  string   `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	SubjectName          string   `protobuf:"bytes,3,opt,name=subjectName,proto3" json:"subjectName,omitempty"`
	ExpireTM             string   `protobuf:"bytes,4,opt,name=expireTM,proto3" json:"expireTM,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddInfraApplyReq) Reset()         { *m = AddInfraApplyReq{} }
func (m *AddInfraApplyReq) String() string { return proto.CompactTextString(m) }
func (*AddInfraApplyReq) ProtoMessage()    {}
func (*AddInfraApplyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1659b64737a352e6, []int{4}
}

func (m *AddInfraApplyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddInfraApplyReq.Unmarshal(m, b)
}
func (m *AddInfraApplyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddInfraApplyReq.Marshal(b, m, deterministic)
}
func (m *AddInfraApplyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddInfraApplyReq.Merge(m, src)
}
func (m *AddInfraApplyReq) XXX_Size() int {
	return xxx_messageInfo_AddInfraApplyReq.Size(m)
}
func (m *AddInfraApplyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddInfraApplyReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddInfraApplyReq proto.InternalMessageInfo

func (m *AddInfraApplyReq) GetDeviceCode() string {
	if m != nil {
		return m.DeviceCode
	}
	return ""
}

func (m *AddInfraApplyReq) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *AddInfraApplyReq) GetSubjectName() string {
	if m != nil {
		return m.SubjectName
	}
	return ""
}

func (m *AddInfraApplyReq) GetExpireTM() string {
	if m != nil {
		return m.ExpireTM
	}
	return ""
}

type AddInfraApplyReply struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddInfraApplyReply) Reset()         { *m = AddInfraApplyReply{} }
func (m *AddInfraApplyReply) String() string { return proto.CompactTextString(m) }
func (*AddInfraApplyReply) ProtoMessage()    {}
func (*AddInfraApplyReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1659b64737a352e6, []int{5}
}

func (m *AddInfraApplyReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddInfraApplyReply.Unmarshal(m, b)
}
func (m *AddInfraApplyReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddInfraApplyReply.Marshal(b, m, deterministic)
}
func (m *AddInfraApplyReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddInfraApplyReply.Merge(m, src)
}
func (m *AddInfraApplyReply) XXX_Size() int {
	return xxx_messageInfo_AddInfraApplyReply.Size(m)
}
func (m *AddInfraApplyReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AddInfraApplyReply.DiscardUnknown(m)
}

var xxx_messageInfo_AddInfraApplyReply proto.InternalMessageInfo

func (m *AddInfraApplyReply) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

// Update
type UpdateInfraApplyReq struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ExpireTM             string   `protobuf:"bytes,3,opt,name=expireTM,proto3" json:"expireTM,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateInfraApplyReq) Reset()         { *m = UpdateInfraApplyReq{} }
func (m *UpdateInfraApplyReq) String() string { return proto.CompactTextString(m) }
func (*UpdateInfraApplyReq) ProtoMessage()    {}
func (*UpdateInfraApplyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1659b64737a352e6, []int{6}
}

func (m *UpdateInfraApplyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateInfraApplyReq.Unmarshal(m, b)
}
func (m *UpdateInfraApplyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateInfraApplyReq.Marshal(b, m, deterministic)
}
func (m *UpdateInfraApplyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateInfraApplyReq.Merge(m, src)
}
func (m *UpdateInfraApplyReq) XXX_Size() int {
	return xxx_messageInfo_UpdateInfraApplyReq.Size(m)
}
func (m *UpdateInfraApplyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateInfraApplyReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateInfraApplyReq proto.InternalMessageInfo

func (m *UpdateInfraApplyReq) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *UpdateInfraApplyReq) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *UpdateInfraApplyReq) GetExpireTM() string {
	if m != nil {
		return m.ExpireTM
	}
	return ""
}

type UpdateInfraApplyReply struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateInfraApplyReply) Reset()         { *m = UpdateInfraApplyReply{} }
func (m *UpdateInfraApplyReply) String() string { return proto.CompactTextString(m) }
func (*UpdateInfraApplyReply) ProtoMessage()    {}
func (*UpdateInfraApplyReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1659b64737a352e6, []int{7}
}

func (m *UpdateInfraApplyReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateInfraApplyReply.Unmarshal(m, b)
}
func (m *UpdateInfraApplyReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateInfraApplyReply.Marshal(b, m, deterministic)
}
func (m *UpdateInfraApplyReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateInfraApplyReply.Merge(m, src)
}
func (m *UpdateInfraApplyReply) XXX_Size() int {
	return xxx_messageInfo_UpdateInfraApplyReply.Size(m)
}
func (m *UpdateInfraApplyReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateInfraApplyReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateInfraApplyReply proto.InternalMessageInfo

func (m *UpdateInfraApplyReply) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

// Delete
type DelInfraApplyReq struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Uid                  string   `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelInfraApplyReq) Reset()         { *m = DelInfraApplyReq{} }
func (m *DelInfraApplyReq) String() string { return proto.CompactTextString(m) }
func (*DelInfraApplyReq) ProtoMessage()    {}
func (*DelInfraApplyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1659b64737a352e6, []int{8}
}

func (m *DelInfraApplyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelInfraApplyReq.Unmarshal(m, b)
}
func (m *DelInfraApplyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelInfraApplyReq.Marshal(b, m, deterministic)
}
func (m *DelInfraApplyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelInfraApplyReq.Merge(m, src)
}
func (m *DelInfraApplyReq) XXX_Size() int {
	return xxx_messageInfo_DelInfraApplyReq.Size(m)
}
func (m *DelInfraApplyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DelInfraApplyReq.DiscardUnknown(m)
}

var xxx_messageInfo_DelInfraApplyReq proto.InternalMessageInfo

func (m *DelInfraApplyReq) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *DelInfraApplyReq) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type DelInfraApplyReply struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelInfraApplyReply) Reset()         { *m = DelInfraApplyReply{} }
func (m *DelInfraApplyReply) String() string { return proto.CompactTextString(m) }
func (*DelInfraApplyReply) ProtoMessage()    {}
func (*DelInfraApplyReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1659b64737a352e6, []int{9}
}

func (m *DelInfraApplyReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelInfraApplyReply.Unmarshal(m, b)
}
func (m *DelInfraApplyReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelInfraApplyReply.Marshal(b, m, deterministic)
}
func (m *DelInfraApplyReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelInfraApplyReply.Merge(m, src)
}
func (m *DelInfraApplyReply) XXX_Size() int {
	return xxx_messageInfo_DelInfraApplyReply.Size(m)
}
func (m *DelInfraApplyReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DelInfraApplyReply.DiscardUnknown(m)
}

var xxx_messageInfo_DelInfraApplyReply proto.InternalMessageInfo

func (m *DelInfraApplyReply) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*ModelPage)(nil), "InfraApply.ModelPage")
	proto.RegisterType((*ListInfraApplyReq)(nil), "InfraApply.ListInfraApplyReq")
	proto.RegisterType((*ListInfraApplyReply)(nil), "InfraApply.ListInfraApplyReply")
	proto.RegisterType((*DetailInfraApplyReply)(nil), "InfraApply.DetailInfraApplyReply")
	proto.RegisterType((*AddInfraApplyReq)(nil), "InfraApply.AddInfraApplyReq")
	proto.RegisterType((*AddInfraApplyReply)(nil), "InfraApply.AddInfraApplyReply")
	proto.RegisterType((*UpdateInfraApplyReq)(nil), "InfraApply.UpdateInfraApplyReq")
	proto.RegisterType((*UpdateInfraApplyReply)(nil), "InfraApply.UpdateInfraApplyReply")
	proto.RegisterType((*DelInfraApplyReq)(nil), "InfraApply.DelInfraApplyReq")
	proto.RegisterType((*DelInfraApplyReply)(nil), "InfraApply.DelInfraApplyReply")
}

func init() { proto.RegisterFile("microservcice.proto", fileDescriptor_1659b64737a352e6) }

var fileDescriptor_1659b64737a352e6 = []byte{
	// 613 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x95, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x65, 0x27, 0x4d, 0x9b, 0xa9, 0xa8, 0xc2, 0x86, 0x54, 0x56, 0x14, 0x4a, 0x6a, 0x81,
	0x68, 0xa3, 0x2a, 0x86, 0xc0, 0x85, 0xde, 0x02, 0x11, 0x92, 0xa5, 0xa6, 0x8a, 0x4c, 0x10, 0x2a,
	0xb7, 0xad, 0x3d, 0xa4, 0x46, 0x6e, 0x6c, 0xec, 0x4d, 0x48, 0x38, 0x70, 0xc8, 0x91, 0x2b, 0x27,
	0x2e, 0xbc, 0x14, 0xaf, 0xc0, 0x9d, 0x57, 0x40, 0xbb, 0x71, 0x62, 0xaf, 0xf3, 0x07, 0x89, 0x9b,
	0x67, 0x67, 0x3f, 0xcf, 0x6f, 0xbe, 0x19, 0xcb, 0x50, 0xbe, 0x75, 0xed, 0xd0, 0x8f, 0x30, 0x1c,
	0xdb, 0xae, 0x8d, 0xcd, 0x20, 0xf4, 0x99, 0x4f, 0xc0, 0x1c, 0x7e, 0x08, 0x69, 0x3b, 0x08, 0xbc,
	0x69, 0xb5, 0x36, 0xf0, 0xfd, 0x81, 0x87, 0x06, 0x0d, 0x5c, 0x83, 0x0e, 0x87, 0x3e, 0xa3, 0xcc,
	0xf5, 0x87, 0xd1, 0xfc, 0xa6, 0xfe, 0x0e, 0x8a, 0x5d, 0xdf, 0x41, 0xaf, 0x47, 0x07, 0x48, 0x34,
	0xd8, 0x0d, 0xe8, 0x00, 0x4d, 0x67, 0xa2, 0x29, 0x75, 0xe5, 0x64, 0xc7, 0x5a, 0x84, 0xa4, 0x0a,
	0x7b, 0xfc, 0xf1, 0x8d, 0xfb, 0x05, 0x35, 0x55, 0xa4, 0x96, 0x31, 0xb9, 0x07, 0x3b, 0xcc, 0x67,
	0xd4, 0xd3, 0x72, 0x22, 0x31, 0x0f, 0x74, 0x0a, 0x77, 0x2f, 0xdc, 0x88, 0x25, 0x20, 0x16, 0x7e,
	0xfa, 0xcf, 0x02, 0x87, 0x50, 0x88, 0x90, 0x86, 0xf6, 0x8d, 0xa8, 0x50, 0xb4, 0xe2, 0x48, 0xff,
	0xa1, 0x40, 0x39, 0x5b, 0x23, 0xf0, 0xa6, 0xe4, 0x14, 0xf2, 0x5c, 0x2b, 0x4a, 0xec, 0xb7, 0x2a,
	0xcd, 0x24, 0xdf, 0x5c, 0xf6, 0x6a, 0x89, 0x2b, 0xe4, 0x05, 0x14, 0x42, 0xb4, 0xfd, 0xd0, 0xd1,
	0xd4, 0x7a, 0xee, 0x64, 0xbf, 0x75, 0x9c, 0xbe, 0xdc, 0x41, 0x46, 0x5d, 0x2f, 0xf3, 0x76, 0x2b,
	0x16, 0x90, 0x1a, 0x14, 0x71, 0x72, 0x43, 0x47, 0x11, 0x43, 0x47, 0x80, 0xed, 0x59, 0xc9, 0x81,
	0xfe, 0x47, 0x81, 0xca, 0x5a, 0x3d, 0x39, 0x00, 0xd5, 0xec, 0xc4, 0xed, 0xab, 0x66, 0x87, 0x1c,
	0x01, 0x38, 0x38, 0x76, 0x6d, 0x7c, 0xe5, 0x3b, 0xf3, 0xde, 0x8b, 0x56, 0xea, 0x84, 0x7b, 0x46,
	0xb9, 0x1a, 0xc3, 0xb8, 0xfd, 0x45, 0x28, 0x7c, 0x61, 0x94, 0x8d, 0x22, 0x2d, 0x1f, 0xfb, 0x22,
	0x22, 0x52, 0x87, 0xfd, 0x68, 0x74, 0xfd, 0x11, 0x6d, 0x76, 0x49, 0x6f, 0x51, 0xdb, 0x11, 0xc9,
	0xf4, 0x11, 0x77, 0x3b, 0xc4, 0xb1, 0x8b, 0x9f, 0x4d, 0x47, 0x2b, 0x88, 0xf4, 0x32, 0xe6, 0x39,
	0x9c, 0x04, 0x6e, 0x88, 0xfd, 0xae, 0xb6, 0x3b, 0xcf, 0x2d, 0xe2, 0x44, 0xd7, 0xef, 0x6a, 0x7b,
	0x69, 0x5d, 0xbf, 0xab, 0xcf, 0x14, 0x28, 0xb5, 0x1d, 0x47, 0x1e, 0xb8, 0xdc, 0x9c, 0xb2, 0xd2,
	0x5c, 0x09, 0x72, 0x23, 0xd7, 0x89, 0xbb, 0xe6, 0x8f, 0x59, 0xf8, 0xdc, 0x5a, 0xf8, 0x25, 0x60,
	0x5e, 0x06, 0xd4, 0xcf, 0x80, 0x64, 0x18, 0xb8, 0xe5, 0x87, 0x7c, 0xca, 0xd1, 0xc8, 0x63, 0x31,
	0x41, 0x1c, 0xe9, 0x57, 0x50, 0x7e, 0x1b, 0x38, 0x94, 0xa1, 0x0c, 0x9d, 0x9d, 0x50, 0xe2, 0xb3,
	0x2a, 0xf9, 0x9c, 0x06, 0xc9, 0x65, 0x40, 0x0c, 0xa8, 0xac, 0xbe, 0x7a, 0x1b, 0xcb, 0x73, 0x28,
	0x75, 0xd0, 0xdb, 0x04, 0x52, 0x14, 0x20, 0x2b, 0x6e, 0xf1, 0x7e, 0x33, 0xaa, 0x2d, 0x35, 0x5a,
	0x3f, 0xf3, 0x00, 0xe6, 0xe5, 0x6b, 0xab, 0xdd, 0xee, 0xf5, 0x2e, 0xae, 0xc8, 0x4c, 0x81, 0x03,
	0xf9, 0xfb, 0x21, 0xf7, 0xd3, 0xfb, 0xbf, 0xf2, 0xfd, 0x56, 0x1f, 0x6c, 0x4b, 0x07, 0xde, 0x54,
	0x7f, 0x32, 0xfb, 0xf5, 0xfb, 0xbb, 0xda, 0xd0, 0x1f, 0x19, 0xa9, 0x8b, 0x49, 0x49, 0x43, 0xd6,
	0x9c, 0x2b, 0x0d, 0xf2, 0x15, 0xee, 0x48, 0x13, 0x23, 0xb5, 0x74, 0x8d, 0xec, 0x42, 0x55, 0x8f,
	0xb6, 0x64, 0x39, 0x80, 0x21, 0x00, 0x4e, 0xf5, 0x87, 0x1b, 0x00, 0x24, 0x09, 0xaf, 0xff, 0x4d,
	0x81, 0x52, 0x76, 0x52, 0x44, 0xea, 0x73, 0xcd, 0x8a, 0x54, 0x8f, 0xb7, 0x5f, 0xe0, 0x24, 0x2d,
	0x41, 0x72, 0xa6, 0x3f, 0xde, 0x40, 0x92, 0x55, 0xc5, 0x66, 0x48, 0xe3, 0x94, 0xcd, 0xc8, 0xee,
	0x87, 0x6c, 0xc6, 0xea, 0x1e, 0xfc, 0xd3, 0x0c, 0x49, 0x72, 0xae, 0x34, 0x5e, 0xe6, 0xdf, 0xab,
	0xe3, 0xa7, 0xd7, 0x05, 0xf1, 0x6b, 0x78, 0xf6, 0x37, 0x00, 0x00, 0xff, 0xff, 0x8c, 0x40, 0xca,
	0x89, 0x5b, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// INFRAAPPLYClient is the client API for INFRAAPPLY service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type INFRAAPPLYClient interface {
	// List infra apply
	ListInfraApply(ctx context.Context, in *ListInfraApplyReq, opts ...grpc.CallOption) (*ListInfraApplyReply, error)
	// Add infra apply
	AddInfraApply(ctx context.Context, in *AddInfraApplyReq, opts ...grpc.CallOption) (*AddInfraApplyReply, error)
	// Update infra apply
	UpdateInfraApply(ctx context.Context, in *UpdateInfraApplyReq, opts ...grpc.CallOption) (*UpdateInfraApplyReply, error)
	//Delete infra
	DelInfraApply(ctx context.Context, in *DelInfraApplyReq, opts ...grpc.CallOption) (*DelInfraApplyReply, error)
}

type iNFRAAPPLYClient struct {
	cc grpc.ClientConnInterface
}

func NewINFRAAPPLYClient(cc grpc.ClientConnInterface) INFRAAPPLYClient {
	return &iNFRAAPPLYClient{cc}
}

func (c *iNFRAAPPLYClient) ListInfraApply(ctx context.Context, in *ListInfraApplyReq, opts ...grpc.CallOption) (*ListInfraApplyReply, error) {
	out := new(ListInfraApplyReply)
	err := c.cc.Invoke(ctx, "/InfraApply.INFRAAPPLY/ListInfraApply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iNFRAAPPLYClient) AddInfraApply(ctx context.Context, in *AddInfraApplyReq, opts ...grpc.CallOption) (*AddInfraApplyReply, error) {
	out := new(AddInfraApplyReply)
	err := c.cc.Invoke(ctx, "/InfraApply.INFRAAPPLY/AddInfraApply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iNFRAAPPLYClient) UpdateInfraApply(ctx context.Context, in *UpdateInfraApplyReq, opts ...grpc.CallOption) (*UpdateInfraApplyReply, error) {
	out := new(UpdateInfraApplyReply)
	err := c.cc.Invoke(ctx, "/InfraApply.INFRAAPPLY/UpdateInfraApply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iNFRAAPPLYClient) DelInfraApply(ctx context.Context, in *DelInfraApplyReq, opts ...grpc.CallOption) (*DelInfraApplyReply, error) {
	out := new(DelInfraApplyReply)
	err := c.cc.Invoke(ctx, "/InfraApply.INFRAAPPLY/DelInfraApply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// INFRAAPPLYServer is the server API for INFRAAPPLY service.
type INFRAAPPLYServer interface {
	// List infra apply
	ListInfraApply(context.Context, *ListInfraApplyReq) (*ListInfraApplyReply, error)
	// Add infra apply
	AddInfraApply(context.Context, *AddInfraApplyReq) (*AddInfraApplyReply, error)
	// Update infra apply
	UpdateInfraApply(context.Context, *UpdateInfraApplyReq) (*UpdateInfraApplyReply, error)
	//Delete infra
	DelInfraApply(context.Context, *DelInfraApplyReq) (*DelInfraApplyReply, error)
}

// UnimplementedINFRAAPPLYServer can be embedded to have forward compatible implementations.
type UnimplementedINFRAAPPLYServer struct {
}

func (*UnimplementedINFRAAPPLYServer) ListInfraApply(ctx context.Context, req *ListInfraApplyReq) (*ListInfraApplyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListInfraApply not implemented")
}
func (*UnimplementedINFRAAPPLYServer) AddInfraApply(ctx context.Context, req *AddInfraApplyReq) (*AddInfraApplyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddInfraApply not implemented")
}
func (*UnimplementedINFRAAPPLYServer) UpdateInfraApply(ctx context.Context, req *UpdateInfraApplyReq) (*UpdateInfraApplyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateInfraApply not implemented")
}
func (*UnimplementedINFRAAPPLYServer) DelInfraApply(ctx context.Context, req *DelInfraApplyReq) (*DelInfraApplyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelInfraApply not implemented")
}

func RegisterINFRAAPPLYServer(s *grpc.Server, srv INFRAAPPLYServer) {
	s.RegisterService(&_INFRAAPPLY_serviceDesc, srv)
}

func _INFRAAPPLY_ListInfraApply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInfraApplyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(INFRAAPPLYServer).ListInfraApply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/InfraApply.INFRAAPPLY/ListInfraApply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(INFRAAPPLYServer).ListInfraApply(ctx, req.(*ListInfraApplyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _INFRAAPPLY_AddInfraApply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddInfraApplyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(INFRAAPPLYServer).AddInfraApply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/InfraApply.INFRAAPPLY/AddInfraApply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(INFRAAPPLYServer).AddInfraApply(ctx, req.(*AddInfraApplyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _INFRAAPPLY_UpdateInfraApply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateInfraApplyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(INFRAAPPLYServer).UpdateInfraApply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/InfraApply.INFRAAPPLY/UpdateInfraApply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(INFRAAPPLYServer).UpdateInfraApply(ctx, req.(*UpdateInfraApplyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _INFRAAPPLY_DelInfraApply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelInfraApplyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(INFRAAPPLYServer).DelInfraApply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/InfraApply.INFRAAPPLY/DelInfraApply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(INFRAAPPLYServer).DelInfraApply(ctx, req.(*DelInfraApplyReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _INFRAAPPLY_serviceDesc = grpc.ServiceDesc{
	ServiceName: "InfraApply.INFRAAPPLY",
	HandlerType: (*INFRAAPPLYServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListInfraApply",
			Handler:    _INFRAAPPLY_ListInfraApply_Handler,
		},
		{
			MethodName: "AddInfraApply",
			Handler:    _INFRAAPPLY_AddInfraApply_Handler,
		},
		{
			MethodName: "UpdateInfraApply",
			Handler:    _INFRAAPPLY_UpdateInfraApply_Handler,
		},
		{
			MethodName: "DelInfraApply",
			Handler:    _INFRAAPPLY_DelInfraApply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "microservcice.proto",
}
