// Code generated by protoc-gen-go. DO NOT EDIT.
// source: infra_show.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Get
type GetInfraListReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfraListReq) Reset()         { *m = GetInfraListReq{} }
func (m *GetInfraListReq) String() string { return proto.CompactTextString(m) }
func (*GetInfraListReq) ProtoMessage()    {}
func (*GetInfraListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5841f1640e7490e, []int{0}
}

func (m *GetInfraListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfraListReq.Unmarshal(m, b)
}
func (m *GetInfraListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfraListReq.Marshal(b, m, deterministic)
}
func (m *GetInfraListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfraListReq.Merge(m, src)
}
func (m *GetInfraListReq) XXX_Size() int {
	return xxx_messageInfo_GetInfraListReq.Size(m)
}
func (m *GetInfraListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfraListReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfraListReq proto.InternalMessageInfo

type GetInfraListReply struct {
	Infra                []*InfraDetailReply `protobuf:"bytes,1,rep,name=infra,proto3" json:"infra,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetInfraListReply) Reset()         { *m = GetInfraListReply{} }
func (m *GetInfraListReply) String() string { return proto.CompactTextString(m) }
func (*GetInfraListReply) ProtoMessage()    {}
func (*GetInfraListReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5841f1640e7490e, []int{1}
}

func (m *GetInfraListReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfraListReply.Unmarshal(m, b)
}
func (m *GetInfraListReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfraListReply.Marshal(b, m, deterministic)
}
func (m *GetInfraListReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfraListReply.Merge(m, src)
}
func (m *GetInfraListReply) XXX_Size() int {
	return xxx_messageInfo_GetInfraListReply.Size(m)
}
func (m *GetInfraListReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfraListReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfraListReply proto.InternalMessageInfo

func (m *GetInfraListReply) GetInfra() []*InfraDetailReply {
	if m != nil {
		return m.Infra
	}
	return nil
}

type InfraDetailReply struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=Code,proto3" json:"Code,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=Type,proto3" json:"Type,omitempty"`
	Location             string   `protobuf:"bytes,5,opt,name=Location,proto3" json:"Location,omitempty"`
	Description          string   `protobuf:"bytes,6,opt,name=Description,proto3" json:"Description,omitempty"`
	ManagedBy            string   `protobuf:"bytes,7,opt,name=ManagedBy,proto3" json:"ManagedBy,omitempty"`
	Status               string   `protobuf:"bytes,8,opt,name=Status,proto3" json:"Status,omitempty"`
	UpdateTime           string   `protobuf:"bytes,9,opt,name=UpdateTime,proto3" json:"UpdateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfraDetailReply) Reset()         { *m = InfraDetailReply{} }
func (m *InfraDetailReply) String() string { return proto.CompactTextString(m) }
func (*InfraDetailReply) ProtoMessage()    {}
func (*InfraDetailReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5841f1640e7490e, []int{2}
}

func (m *InfraDetailReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfraDetailReply.Unmarshal(m, b)
}
func (m *InfraDetailReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfraDetailReply.Marshal(b, m, deterministic)
}
func (m *InfraDetailReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfraDetailReply.Merge(m, src)
}
func (m *InfraDetailReply) XXX_Size() int {
	return xxx_messageInfo_InfraDetailReply.Size(m)
}
func (m *InfraDetailReply) XXX_DiscardUnknown() {
	xxx_messageInfo_InfraDetailReply.DiscardUnknown(m)
}

var xxx_messageInfo_InfraDetailReply proto.InternalMessageInfo

func (m *InfraDetailReply) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *InfraDetailReply) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *InfraDetailReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InfraDetailReply) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *InfraDetailReply) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *InfraDetailReply) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *InfraDetailReply) GetManagedBy() string {
	if m != nil {
		return m.ManagedBy
	}
	return ""
}

func (m *InfraDetailReply) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *InfraDetailReply) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

// Update
type UpdateInfraListReq struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=Code,proto3" json:"Code,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=Type,proto3" json:"Type,omitempty"`
	Location             string   `protobuf:"bytes,5,opt,name=Location,proto3" json:"Location,omitempty"`
	Description          string   `protobuf:"bytes,6,opt,name=Description,proto3" json:"Description,omitempty"`
	ManagedBy            string   `protobuf:"bytes,7,opt,name=ManagedBy,proto3" json:"ManagedBy,omitempty"`
	Status               string   `protobuf:"bytes,8,opt,name=Status,proto3" json:"Status,omitempty"`
	UpdateTime           string   `protobuf:"bytes,9,opt,name=UpdateTime,proto3" json:"UpdateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateInfraListReq) Reset()         { *m = UpdateInfraListReq{} }
func (m *UpdateInfraListReq) String() string { return proto.CompactTextString(m) }
func (*UpdateInfraListReq) ProtoMessage()    {}
func (*UpdateInfraListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5841f1640e7490e, []int{3}
}

func (m *UpdateInfraListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateInfraListReq.Unmarshal(m, b)
}
func (m *UpdateInfraListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateInfraListReq.Marshal(b, m, deterministic)
}
func (m *UpdateInfraListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateInfraListReq.Merge(m, src)
}
func (m *UpdateInfraListReq) XXX_Size() int {
	return xxx_messageInfo_UpdateInfraListReq.Size(m)
}
func (m *UpdateInfraListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateInfraListReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateInfraListReq proto.InternalMessageInfo

func (m *UpdateInfraListReq) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *UpdateInfraListReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *UpdateInfraListReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateInfraListReq) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *UpdateInfraListReq) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *UpdateInfraListReq) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UpdateInfraListReq) GetManagedBy() string {
	if m != nil {
		return m.ManagedBy
	}
	return ""
}

func (m *UpdateInfraListReq) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *UpdateInfraListReq) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

type UpdateInfraListReply struct {
	Result               string   `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateInfraListReply) Reset()         { *m = UpdateInfraListReply{} }
func (m *UpdateInfraListReply) String() string { return proto.CompactTextString(m) }
func (*UpdateInfraListReply) ProtoMessage()    {}
func (*UpdateInfraListReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5841f1640e7490e, []int{4}
}

func (m *UpdateInfraListReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateInfraListReply.Unmarshal(m, b)
}
func (m *UpdateInfraListReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateInfraListReply.Marshal(b, m, deterministic)
}
func (m *UpdateInfraListReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateInfraListReply.Merge(m, src)
}
func (m *UpdateInfraListReply) XXX_Size() int {
	return xxx_messageInfo_UpdateInfraListReply.Size(m)
}
func (m *UpdateInfraListReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateInfraListReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateInfraListReply proto.InternalMessageInfo

func (m *UpdateInfraListReply) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

// Delete infra
type DelInfraReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelInfraReq) Reset()         { *m = DelInfraReq{} }
func (m *DelInfraReq) String() string { return proto.CompactTextString(m) }
func (*DelInfraReq) ProtoMessage()    {}
func (*DelInfraReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5841f1640e7490e, []int{5}
}

func (m *DelInfraReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelInfraReq.Unmarshal(m, b)
}
func (m *DelInfraReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelInfraReq.Marshal(b, m, deterministic)
}
func (m *DelInfraReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelInfraReq.Merge(m, src)
}
func (m *DelInfraReq) XXX_Size() int {
	return xxx_messageInfo_DelInfraReq.Size(m)
}
func (m *DelInfraReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DelInfraReq.DiscardUnknown(m)
}

var xxx_messageInfo_DelInfraReq proto.InternalMessageInfo

func (m *DelInfraReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DelInfraReply struct {
	Result               string   `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelInfraReply) Reset()         { *m = DelInfraReply{} }
func (m *DelInfraReply) String() string { return proto.CompactTextString(m) }
func (*DelInfraReply) ProtoMessage()    {}
func (*DelInfraReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5841f1640e7490e, []int{6}
}

func (m *DelInfraReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelInfraReply.Unmarshal(m, b)
}
func (m *DelInfraReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelInfraReply.Marshal(b, m, deterministic)
}
func (m *DelInfraReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelInfraReply.Merge(m, src)
}
func (m *DelInfraReply) XXX_Size() int {
	return xxx_messageInfo_DelInfraReply.Size(m)
}
func (m *DelInfraReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DelInfraReply.DiscardUnknown(m)
}

var xxx_messageInfo_DelInfraReply proto.InternalMessageInfo

func (m *DelInfraReply) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*GetInfraListReq)(nil), "api.GetInfraListReq")
	proto.RegisterType((*GetInfraListReply)(nil), "api.GetInfraListReply")
	proto.RegisterType((*InfraDetailReply)(nil), "api.InfraDetailReply")
	proto.RegisterType((*UpdateInfraListReq)(nil), "api.UpdateInfraListReq")
	proto.RegisterType((*UpdateInfraListReply)(nil), "api.UpdateInfraListReply")
	proto.RegisterType((*DelInfraReq)(nil), "api.DelInfraReq")
	proto.RegisterType((*DelInfraReply)(nil), "api.DelInfraReply")
}

func init() { proto.RegisterFile("infra_show.proto", fileDescriptor_d5841f1640e7490e) }

var fileDescriptor_d5841f1640e7490e = []byte{
	// 375 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x93, 0xdf, 0x8a, 0xda, 0x40,
	0x14, 0xc6, 0x19, 0xff, 0xa4, 0xe6, 0xd8, 0x56, 0x3d, 0x58, 0x3b, 0x0d, 0xa5, 0xa4, 0xb9, 0xa9,
	0x50, 0x08, 0xc5, 0xde, 0xf6, 0xa2, 0xb4, 0x29, 0x45, 0xb0, 0xbd, 0x88, 0xf6, 0xba, 0xcc, 0xea,
	0xec, 0x3a, 0x10, 0xcd, 0xac, 0x19, 0x91, 0xbc, 0xde, 0x3e, 0xd2, 0xb2, 0x0f, 0xb0, 0xcc, 0x89,
	0xae, 0xd9, 0x28, 0xfb, 0x00, 0x7b, 0x77, 0xce, 0xef, 0xfb, 0x38, 0x99, 0x6f, 0xe6, 0x04, 0xba,
	0x6a, 0x7d, 0xb9, 0x11, 0xff, 0xb3, 0x65, 0xba, 0x0b, 0xf5, 0x26, 0x35, 0x29, 0xd6, 0x85, 0x56,
	0x41, 0x0f, 0x3a, 0xbf, 0xa5, 0x19, 0x5b, 0x6d, 0xa2, 0x32, 0x13, 0xcb, 0xeb, 0xe0, 0x3b, 0xf4,
	0x1e, 0x23, 0x9d, 0xe4, 0xf8, 0x19, 0x9a, 0x34, 0x80, 0x33, 0xbf, 0x3e, 0x6c, 0x8f, 0xde, 0x84,
	0x42, 0xab, 0x90, 0x3c, 0x91, 0x34, 0x42, 0x25, 0xe4, 0x8a, 0x0b, 0x4f, 0x70, 0xcb, 0xa0, 0x5b,
	0xd5, 0xf0, 0x35, 0xd4, 0xc6, 0x11, 0x67, 0x3e, 0x1b, 0x36, 0xe3, 0xda, 0x38, 0x42, 0x84, 0xc6,
	0xcf, 0x74, 0x21, 0x79, 0xcd, 0x67, 0x43, 0x37, 0xa6, 0xda, 0xb2, 0xbf, 0x62, 0x25, 0x79, 0xbd,
	0x60, 0xb6, 0xb6, 0x6c, 0x96, 0x6b, 0xc9, 0x1b, 0x05, 0xb3, 0x35, 0x7a, 0xd0, 0x9a, 0xa4, 0x73,
	0x61, 0x54, 0xba, 0xe6, 0x4d, 0xe2, 0x0f, 0x3d, 0xfa, 0xd0, 0x8e, 0x64, 0x36, 0xdf, 0x28, 0x4d,
	0xb2, 0x43, 0x72, 0x19, 0xe1, 0x7b, 0x70, 0xff, 0x88, 0xb5, 0xb8, 0x92, 0x8b, 0x1f, 0x39, 0x7f,
	0x41, 0xfa, 0x11, 0xe0, 0x00, 0x9c, 0xa9, 0x11, 0x66, 0x9b, 0xf1, 0x16, 0x49, 0xfb, 0x0e, 0x3f,
	0x00, 0xfc, 0xd3, 0x0b, 0x61, 0xe4, 0x4c, 0xad, 0x24, 0x77, 0x49, 0x2b, 0x91, 0xe0, 0x8e, 0x01,
	0x16, 0x6d, 0xf9, 0x36, 0x9f, 0x7d, 0xec, 0x10, 0xfa, 0x27, 0xa9, 0xed, 0x73, 0x0f, 0xc0, 0x89,
	0x65, 0xb6, 0x4d, 0x0c, 0x65, 0x77, 0xe3, 0x7d, 0x17, 0x7c, 0xb4, 0xe7, 0x4c, 0xc8, 0x6c, 0xaf,
	0xe7, 0x10, 0x9d, 0x1d, 0xa3, 0x07, 0x9f, 0xe0, 0xd5, 0xd1, 0xf2, 0xc4, 0xac, 0xd1, 0x0d, 0x03,
	0x97, 0x6c, 0xd3, 0x65, 0xba, 0xc3, 0x6f, 0xf0, 0xb2, 0xbc, 0xb7, 0xd8, 0xa7, 0x1d, 0xad, 0x6c,
	0xb7, 0x37, 0x38, 0x43, 0xed, 0x37, 0x7e, 0x41, 0xa7, 0x92, 0x03, 0xdf, 0x92, 0xf5, 0xf4, 0x4d,
	0xbd, 0x77, 0xe7, 0x05, 0x3b, 0xe6, 0x0b, 0xb4, 0x0e, 0x67, 0xc7, 0x2e, 0xd9, 0x4a, 0x69, 0x3d,
	0xac, 0x10, 0x9d, 0xe4, 0x17, 0x0e, 0xfd, 0x8d, 0x5f, 0xef, 0x03, 0x00, 0x00, 0xff, 0xff, 0xfc,
	0xa6, 0x14, 0x68, 0xa1, 0x03, 0x00, 0x00,
}
